g

diff --git a/.github/actions/prettier-cli-action/action.yml b/.github/actions/prettier-cli-action/action.yml
--- a/.github/actions/prettier-cli-action/action.yml
+++ b/.github/actions/prettier-cli-action/action.yml
@@ -32,7 +32,13 @@ runs:
     - name: Running Prettier
       id: prettier-run
       shell: bash
-      run: echo "prettier-output=$(prettier . --check --no-error-on-unmatched-pattern)" >> $GITHUB_OUTPUT
+      run: |
+        echo "prettier-output=$(prettier . --check --no-error-on-unmatched-pattern)" 
+        || {
+          echo "Follow bellow steps to prettify your code:"
+          echo "Install prettier locally: https://prettier.io/docs/en/install.html"
+          echo "Then format all filles with this command: prettier FILE_NAME --write"
+        }
     - name: Fail On Error
       id: fail-on-error
       if: steps.prettier-run.outputs.prettier-output != 0 && steps.prettier-run.outputs.prettier-output != '' && inputs.fail_on_error
