one file to prettify (#23)
* test prettierrc (#21)

prettier action test (#22)

one file to prettify

check 123

mam dość tego prettiera

EOF prettier

delete github output

na około, ale powinno działać

syntax

pliska

prettify plis plis

get rid of if

nie myśle, że to to, ale może

$-

serio syntax

this should work serio!!!

lets check this pliska oby działało

ok

files_to_check

* solving review issues

* FILES_TO_CHECK

* FILES_TO_CHECK

* a XD

* env.FILES_TO_CHECK

* chore(TECH): move env into step

* check syntax

* echo errors and notices

* together strong

* bly bly

* print each element of loop

* now it should work

* syntax

* maybe check

* to potrzebne? XD

* bez %A0

* small adjustments

* hehe

* delete unnecessary

---------

Co-authored-by: Kacper Zawalski <kacper.zawalski@capgemini.com>

diff --git a/.github/actions/prettier-cli-action/action.yml b/.github/actions/prettier-cli-action/action.yml
--- a/.github/actions/prettier-cli-action/action.yml
+++ b/.github/actions/prettier-cli-action/action.yml
@@ -1,51 +1,43 @@
 name: Prettier Check
-description: 'A simple action which runs the Prettier CLI Check'
+description: 'A action which runs the Prettier CLI Check'
 inputs:
-  prettier_version:
+  prettier-version:
     description: 'The version of prettier to install'
     required: false
-    default: 'latest'
+    default: '3.1.1'
   fail_on_error:
     description: 'Whether the script should fail when linting errors are found'
     required: false
     default: true
-  file_pattern:
-    description: 'The file pattern to scan'
+  files-to-check:
+    description: 'Files to check'
     required: false
     default: '**/*'
-outputs:
-  PRETTIER_OUTPUT:
-    description: 'The output from prettier'
-    value: ${{ steps.prettier-run.outputs.prettier-output }}
 runs:
-  using: 'composite'
+  using: composite
   steps:
-    - name: Installing Prettier
+    - name: Install Prettier through NPM
       id: prettier-install
       shell: bash
-      run: npm install --global prettier@${{ inputs.prettier_version }}
-    - name: Running Prettier
+      run: npm install --global prettier@${{ inputs.prettier-version }}
+    - name: Run Prettier
       id: prettier-run
+      env: 
+        FILES_TO_CHECK: ${{ inputs.files-to-check }}
       shell: bash
       run: |
-        echo "prettier_output=$(prettier --list-different --config .prettierrc.yml --ignore-unknown --no-error-on-unmatched-pattern ${{ inputs.file_pattern }})"\
-        || echo "Problem running prettier with $prettier_output"; exit 1;
-        
-        if [ -z "$prettier_output" ]
-        then
-          echo "There is a nothing to prettify! Great!"
-        else
-          echo "Follow bellow steps to prettify your code:"
-          echo "Install prettier locally: https://prettier.io/docs/en/install.html"
-          echo "Then format all filles with this command: prettier FILE_NAME --write"
-          exit 1
-        fi
-    - name: Fail On Error
-      id: fail-on-error
-      if:  env.PRETTIER_OUTPUT != '' && inputs.fail_on_error
-      shell: bash
-      run: |
-        echo "Follow bellow steps to prettify your code:"
-        echo "Install prettier locally: https://prettier.io/docs/en/install.html"
-        echo "Then format all filles with this command: prettier FILE_NAME --write"
+        prettier_output="$(
+        prettier --list-different \
+        --config .prettierrc.yml \
+        --ignore-unknown \
+        --no-error-on-unmatched-pattern \
+        $FILES_TO_CHECK)" \
+        || ( 
+        for file_to_prettify in $prettier_output; do
+          echo "::error:: File to Prettify: $file_to_prettify"
+        done        
+        echo '::notice::Follow bellow steps to prettify your code:%0A' \
+        '- Install prettier locally: https://prettier.io/docs/en/install.html%0A' \
+        '- Then format all filles with this command: prettier FILE_NAME --write'
         exit 1
+        )
