prettier action test (#22)

diff --git a/.github/actions/prettier-cli-action/action.yml b/.github/actions/prettier-cli-action/action.yml
--- a/.github/actions/prettier-cli-action/action.yml
+++ b/.github/actions/prettier-cli-action/action.yml
@@ -1,10 +1,6 @@
 name: Prettier Check
 description: 'A simple action which runs the Prettier CLI Check'
 inputs:
-  config_path:
-    description: 'The path to the prettierrc file'
-    required: false
-    default: ''
   prettier_version:
     description: 'The version of prettier to install'
     required: false
@@ -13,8 +9,12 @@ inputs:
     description: 'Whether the script should fail when linting errors are found'
     required: false
     default: true
+  file_pattern:
+    description: 'The file pattern to scan'
+    required: false
+    default: '**/*'
 outputs:
-  prettier_output:
+  PRETTIER_OUTPUT:
     description: 'The output from prettier'
     value: ${{ steps.prettier-run.outputs.prettier-output }}
 runs:
@@ -28,13 +28,21 @@ runs:
       id: prettier-run
       shell: bash
       run: |
-        mapfile -t my_array < <(git diff --name-only)
-        for element in "${my_array[@]}"; do
-          echo "prettier-output=$(prettier $element --config ${{ inputs.config_path }} --list-different --no-error-on-unmatched-pattern)"
-        done
+        echo "prettier_output=$(prettier --list-different --config .prettierrc.yml --ignore-unknown --no-error-on-unmatched-pattern ${{ inputs.file_pattern }})"\
+        || echo "Problem running prettier with $prettier_output"; exit 1;
+        
+        if [ -z "$prettier_output" ]
+        then
+          echo "There is a nothing to prettify! Great!"
+        else
+          echo "Follow bellow steps to prettify your code:"
+          echo "Install prettier locally: https://prettier.io/docs/en/install.html"
+          echo "Then format all filles with this command: prettier FILE_NAME --write"
+          exit 1
+        fi
     - name: Fail On Error
       id: fail-on-error
-      if: env.PRETTIER_OUTPUT != '' && inputs.fail_on_error
+      if:  env.PRETTIER_OUTPUT != '' && inputs.fail_on_error
       shell: bash
       run: |
         echo "Follow bellow steps to prettify your code:"
